name: currency-converter
services:
  api:
    build:
      context: .
      dockerfile: ./Currency.Api/Dockerfile
    container_name: currency-converter-api
    image: currency-converter-api:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - TZ=Europe/Moscow
      - ASPNETCORE_ENVIRONMENT=Development
        
  redis:
    image: redis:latest
    container_name: currency-converter-redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6390:6379"

volumes:
  redis_data: