name: currency-converter
services:
  api:
    build:
      context: .
      dockerfile: ./Currency.Api/Dockerfile
    container_name: currency-converter-api
    image: currency-converter-api:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - currency_network
        
networks:
  currency_network:
    name: currency_network
    external: true