name: worker-node-1
services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - currency_redis_data:/data
    ports:
      - "6390:6379"
    networks:
      - currency_network
  
  redis-init:
    image: redis:7
    depends_on:
      - redis
    networks:
      - currency_network
    entrypoint: /bin/sh
    command:
      - -c
      - |
        until redis-cli -h redis ping; do
          echo 'Waiting for Redis...';
          sleep 1;
        done;
        redis-cli -h redis < /data/init-redis.redis
    volumes:
      - ../../resources/scripts/init-redis.redis:/data/init-redis.redis
  
  elasticsearch:
    image: elasticsearch:9.0.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - currency_elasticsearch_volume:/usr/share/elasticsearch/data
    networks:
      - currency_network
        
  wiremock:
    image: wiremock/wiremock:2.35.0
    ports:
      - "8085:8080"
    volumes:
      - ./resources/WireMock:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    networks:
      - currency_network

networks:
  currency_network:
    name: currency_network
    external: true

volumes:
  currency_redis_data:
  currency_elasticsearch_volume: