name: Testing
run-name: Testing workflow
on:
  push:
    branches: [ test ]
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/currency-api

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.tag.outputs.tag }}
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/currency-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image tag
        id: tag
        run: echo "tag=test-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ steps.tag.outputs.tag }} -f src/Currency.Api/Dockerfile src
          docker push $IMAGE_NAME:${{ steps.tag.outputs.tag }}
  
  unit-tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.301'

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Restore dependencies
        working-directory: ./src
        run: dotnet restore

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Add .NET tools to PATH
        run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      - name: Run unit tests with coverage via Makefile
        run: make coverage

      - name: Append coverage summary to GitHub
        if: always()
        run: cat ./TestResults/CoverageReport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

      - name: Upload full coverage report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./TestResults/CoverageReport
        
  integration-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.301'
          
      - name: Inject IMAGE_TAG into .env file
        run: echo "IMAGE_TAG=${{ needs.build.outputs.image_tag }}" >> .env

      - name: Restore and Build
        run: |
          dotnet restore ./src/currency-converter.sln
          dotnet build ./src/currency-converter.sln --configuration Release --no-restore
          
      - name: Start Currency API & WireMock
        run: make integration_tests_up IMAGE_TAG=${{ needs.build.outputs.image_tag }}

      - name: Run Integration Tests
        run: make test CATEGORY=Integration
        
      - name: Stop API & WireMock
        if: always()
        run: make integration_tests_down